export {
  type AbstractIterator,
  createIteratorItemRef,
  createIteratorRef,
  type IterationItem,
  type IteratorDelegate,
  type OpaqueIterationItem,
  type OpaqueIterator,
  setIterableHooks,
} from './lib/iterable';
export {
  childRefFor,
  childRefFromParts,
  createComputeRef,
  createConstRef,
  createDebugAliasRef,
  createInvokableRef,
  createPrimitiveRef,
  createReadOnlyRef,
  createUnboundRef,
  FALSE_REFERENCE,
  isConstRef,
  isInvokableRef,
  isUpdatableRef,
  NULL_REFERENCE,
  REFERENCE,
  type Reference,
  type ReferenceEnvironment,
  setReferenceHooks,
  TRUE_REFERENCE,
  UNDEFINED_REFERENCE,
  updateRef,
  valueForRef,
} from './lib/reference';
