name: "Size: main"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm build

      - name: "Get estimated sizes for production outputs"
        id: main-dev
        run: |
          mkdir -p main
          node ./bin/minify-assets.sh > ./main/out.txt

      - uses: actions/upload-artifact@v4
        with:
          name: sizes-main
          path: main/
          overwrite: true
